const SET_FLIGHTS = "SET_FLIGHTS";
const SELECT_INBOUND_FLIGHT = "SELECT_INBOUND_FLIGHT";
const SELECT_OUTBOUND_FLIGHT = "SELECT_OUTBOUND_FLIGHT";
const CREATE_BOOKING = "CREATE_BOOKING";

export {
    SET_FLIGHTS,
    SELECT_INBOUND_FLIGHT,
    SELECT_OUTBOUND_FLIGHT,
    CREATE_BOOKING
};